--- не сработал конфиг
--- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=my_db;responseBuffering=adaptive
    username: bestuser
    password: J,]tlbYbnmcz3+idfL7NdjhWjV
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext